# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

Settings:
  Port: 3978
  LuisAppId: ""
  # LUIS authoring key from LUIS portal or LUIS Cognitive Service subscription key
  LuisAPIKey: "" 
  # LUIS endpoint host name, ie "westus.api.cognitive.microsoft.com"
  LuisAPIHostName: "" 
  AppId: ""
  AppPassword: ""